//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp.Generated
{
    public struct BoatInputSerializer : ICommandDataSerializer<BoatInput>
    {
        public void Serialize(ref DataStreamWriter writer, in BoatInput data)
        {
        }

        public void Deserialize(ref DataStreamReader reader, ref BoatInput data)
        {
        }

        public void Serialize(ref DataStreamWriter writer, in BoatInput data, in BoatInput baseline, NetworkCompressionModel compressionModel)
        {
        }

        public void Deserialize(ref DataStreamReader reader, ref BoatInput data, in BoatInput baseline, NetworkCompressionModel compressionModel)
        {
        }
    }
    public class BoatInputSendCommandSystem : CommandSendSystem<BoatInputSerializer, BoatInput>
    {
        [BurstCompile]
        struct SendJob : IJobEntityBatch
        {
            public SendJobData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendJob{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
    public class BoatInputReceiveCommandSystem : CommandReceiveSystem<BoatInputSerializer, BoatInput>
    {
        [BurstCompile]
        struct ReceiveJob : IJobEntityBatch
        {
            public ReceiveJobData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var recvJob = new ReceiveJob{data = InitJobData()};
            ScheduleJobData(recvJob);
        }
    }
}
