//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp.Generated
{
    public struct BoatMouseInputSerializer : ICommandDataSerializer<BoatMouseInput>
    {
        public void Serialize(ref DataStreamWriter writer, in BoatMouseInput data)
        {
            writer.WriteFloat(data.AimPosition.x);
            writer.WriteFloat(data.AimPosition.y);
            writer.WriteFloat(data.AimPosition.z);
        }

        public void Deserialize(ref DataStreamReader reader, ref BoatMouseInput data)
        {
            data.AimPosition.x = reader.ReadFloat();
            data.AimPosition.y = reader.ReadFloat();
            data.AimPosition.z = reader.ReadFloat();
        }

        public void Serialize(ref DataStreamWriter writer, in BoatMouseInput data, in BoatMouseInput baseline, NetworkCompressionModel compressionModel)
        {
            writer.WritePackedFloatDelta(data.AimPosition.x, baseline.AimPosition.x, compressionModel);
            writer.WritePackedFloatDelta(data.AimPosition.y, baseline.AimPosition.y, compressionModel);
            writer.WritePackedFloatDelta(data.AimPosition.z, baseline.AimPosition.z, compressionModel);
        }

        public void Deserialize(ref DataStreamReader reader, ref BoatMouseInput data, in BoatMouseInput baseline, NetworkCompressionModel compressionModel)
        {
            data.AimPosition.x = reader.ReadPackedFloatDelta(baseline.AimPosition.x, compressionModel);
            data.AimPosition.y = reader.ReadPackedFloatDelta(baseline.AimPosition.y, compressionModel);
            data.AimPosition.z = reader.ReadPackedFloatDelta(baseline.AimPosition.z, compressionModel);
        }
    }
    public class BoatMouseInputSendCommandSystem : CommandSendSystem<BoatMouseInputSerializer, BoatMouseInput>
    {
        [BurstCompile]
        struct SendJob : IJobEntityBatch
        {
            public SendJobData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendJob{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
    public class BoatMouseInputReceiveCommandSystem : CommandReceiveSystem<BoatMouseInputSerializer, BoatMouseInput>
    {
        [BurstCompile]
        struct ReceiveJob : IJobEntityBatch
        {
            public ReceiveJobData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var recvJob = new ReceiveJob{data = InitJobData()};
            ScheduleJobData(recvJob);
        }
    }
}
