//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using Unity.Entities;
using Unity.NetCode;
using Assembly_CSharp.Generated;

namespace Assembly_CSharp.Generated
{
    [UpdateInGroup(typeof(ClientAndServerInitializationSystemGroup))]
    public class GhostComponentSerializerRegistrationSystem : SystemBase
    {
        protected override void OnCreate()
        {
            var ghostCollectionSystem = World.GetOrCreateSystem<GhostCollectionSystem>();
            ghostCollectionSystem.AddSerializer(BoatChildrenRotationProxyGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(HealthComponentGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(PlayerInventoryComponentGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(TranslationLowPrecGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(RotationLowPrecGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(RotationSendChildGhostComponentSerializer.State);
        }

        protected override void OnUpdate()
        {
            var parentGroup = World.GetExistingSystem<InitializationSystemGroup>();
            if (parentGroup != null)
            {
                parentGroup.RemoveSystemFromUpdateList(this);
            }
        }
    }
}