//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;


namespace Assembly_CSharp.Generated
{
    [BurstCompile]
    public struct ShootCommandSerializer : IComponentData, IRpcCommandSerializer<ShootCommand>
    {
        public void Serialize(ref DataStreamWriter writer, in RpcSerializerState state, in ShootCommand data)
        {
            writer.WriteFloat(data.TargetPosition.x);
            writer.WriteFloat(data.TargetPosition.y);
            writer.WriteFloat(data.TargetPosition.z);
        }

        public void Deserialize(ref DataStreamReader reader, in RpcDeserializerState state,  ref ShootCommand data)
        {
            data.TargetPosition.x = reader.ReadFloat();
            data.TargetPosition.y = reader.ReadFloat();
            data.TargetPosition.z = reader.ReadFloat();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<ShootCommandSerializer, ShootCommand>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class ShootCommandRpcCommandRequestSystem : RpcCommandRequestSystem<ShootCommandSerializer, ShootCommand>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
